// Generated by Wrangler on Thu Jun 27 2024 21:20:38 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	AUTH_SECRET: string;
	AUTH_TRUST_HOST: string;
	TIDB_HTTP_URL: string;
	DB: D1Database;
}
