#:schema node_modules/wrangler/config-schema.json
name = "cf-next-drizzle-d1-stack"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
