import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from '@/app/dashboard/Header'; // 新しく追加

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header /> {/* 新しく追加 */}
      <main className="flex-grow">
        {children}
      </main>
    </>
  );
}
